### ISSUE TITLE
无法对QQ，微信进行存储隔离

### ISSUE THREAD

**Issue by Sdarfeesh** [wenxuanjun/NoLitter#15]
`[ 2023-02-26T18:18:16.441    10294:  2260:  2260 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mm
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:18:25.404    10274:  2447:  2447 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:18:40.274    10274:  2933:  2933 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:18:57.974    10294:  3761:  3761 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mm
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:19:03.224    10274:  4078:  4078 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:19:09.384    10294:  4607:  4607 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mm
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:19:19.289    10247:  5085:  5085 I/LSPosed-Bridge  ] [NoLitter] com.aliucord: Initializing, Preferences fetched: XposedPreference(forcedMode=true, allowPublicDirs=false, additionalHooks=false, redirectStyle=data, debugMode=true)
[ 2023-02-26T18:19:20.175    10247:  5085:  5085 I/LSPosed-Bridge  ] [NoLitter] com.aliucord: Redirecting, /storage/emulated/0 -> /storage/emulated/0/Android/data/com.aliucord/sdcard
[ 2023-02-26T18:19:31.563    10305:  6273:  6273 I/LSPosed-Bridge  ] [NoLitter] org.havenapp.main: Initializing, Preferences fetched: XposedPreference(forcedMode=true, allowPublicDirs=false, additionalHooks=false, redirectStyle=data, debugMode=true)
[ 2023-02-26T18:29:21.696    10274:  7797:  7797 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:29:35.854    10274:  9250:  9250 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:29:41.622    10274:  9526:  9526 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:29:52.320    10274:  9916:  9916 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:30:09.971    10274: 10134: 10134 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:30:23.793    10274: 10869: 10869 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:30:28.016    10274: 11042: 11042 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:30:34.355    10274: 11202: 11202 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
[ 2023-02-26T18:30:41.525    10274: 11679: 11679 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content, url: content://lantian.nolitter.provider/main/com.tencent.mobileqq
	at GN.beforeHookedMethod(SourceFile:494)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1223)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
`

**Comment by wenxuanjun** [comment]
原因同 #4 所述（虽然还有其他未知原因导致`ContentProvider`获取失败），因此先关闭此 Issue。
