### ISSUE TITLE
alpha版本，Android12，高德地图 8.60.4.2780，无法隔离

### ISSUE THREAD

**Issue by xixiha5230** [wenxuanjun/NoLitter#3]
`----part 3 start----
[ 2022-08-24T01:09:47.086    10229: 26544: 26544 I/LSPosed-Bridge  ] Loading module lantian.nolitter from /data/app/~~xcEQwkxx6sbi4ourOADqjw==/lantian.nolitter-E0PEnGQaGzCbdLTRipPuUQ==/base.apk
[ 2022-08-24T01:09:47.097    10229: 26544: 26544 I/LSPosed-Bridge  ]   Loading class lantian.nolitter.XposedHook
[ 2022-08-24T01:09:47.166    10229: 26544: 26544 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content
	at lantian.nolitter.XposedHook.f(Unknown Source:33)
	at EM.beforeHookedMethod(SourceFile:5)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[ 2022-08-24T01:09:47.197    10202:  3799: 17804 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/autonavi/autonavi_heap_error_log.txt_tmp
[ 2022-08-24T01:09:47.320    10202:  3799: 17824 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml
[ 2022-08-24T01:09:47.345    10202:  3799: 17824 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/.DataStorage/ContextData.xml
[ 2022-08-24T01:09:47.507    10229: 26611: 26611 I/LSPosed-Bridge  ] Loading module lantian.nolitter from /data/app/~~xcEQwkxx6sbi4ourOADqjw==/lantian.nolitter-E0PEnGQaGzCbdLTRipPuUQ==/base.apk
[ 2022-08-24T01:09:47.514    10229: 26611: 26611 I/LSPosed-Bridge  ]   Loading class lantian.nolitter.XposedHook
[ 2022-08-24T01:09:47.563    10229: 26611: 26611 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content
	at lantian.nolitter.XposedHook.f(Unknown Source:33)
	at EM.beforeHookedMethod(SourceFile:5)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[ 2022-08-24T01:09:48.354    10202:  3799: 26608 I/LSPosed-Bridge  ] scan result: content://media/external_primary/file/2262
[ 2022-08-24T01:09:48.359    10202:  3799: 26610 I/LSPosed-Bridge  ] scan result: content://media/external_primary/file/2263
[ 2022-08-24T01:09:48.663    10202:  3799: 17822 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml
[ 2022-08-24T01:09:48.674    10229: 26690: 26690 I/LSPosed-Bridge  ] Loading module lantian.nolitter from /data/app/~~xcEQwkxx6sbi4ourOADqjw==/lantian.nolitter-E0PEnGQaGzCbdLTRipPuUQ==/base.apk
[ 2022-08-24T01:09:48.682    10229: 26690: 26690 I/LSPosed-Bridge  ]   Loading class lantian.nolitter.XposedHook
[ 2022-08-24T01:09:48.682    10202:  3799: 17787 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/.DataStorage/ContextData.xml
[ 2022-08-24T01:09:48.754    10229: 26690: 26690 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content
	at lantian.nolitter.XposedHook.f(Unknown Source:33)
	at EM.beforeHookedMethod(SourceFile:5)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[ 2022-08-24T01:09:48.781    10202:  3799:  5453 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/autonavi/location/location_heap_error_log.txt_tmp
[ 2022-08-24T01:09:48.912    10202:  3799:  5453 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/.UTSystemConfig/Global/Alvin2.xml
[ 2022-08-24T01:09:48.956    10202:  3799: 17789 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/.DataStorage/ContextData.xml
[ 2022-08-24T01:09:49.332    10229: 26915: 26915 I/LSPosed-Bridge  ] Loading module lantian.nolitter from /data/app/~~xcEQwkxx6sbi4ourOADqjw==/lantian.nolitter-E0PEnGQaGzCbdLTRipPuUQ==/base.apk
[ 2022-08-24T01:09:49.352    10229: 26915: 26915 I/LSPosed-Bridge  ]   Loading class lantian.nolitter.XposedHook
[ 2022-08-24T01:09:49.421    10229: 26915: 26915 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content
	at lantian.nolitter.XposedHook.f(Unknown Source:33)
	at EM.beforeHookedMethod(SourceFile:5)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[ 2022-08-24T01:09:49.622    10229: 26611: 26965 I/LSPosed-Bridge  ] Crash unexpectedly: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at akh.<init>(LPDbManager.java:39)
	at akg.<init>(DataManager.java:145)
	at ajo.handleMessage(RemoteHandler.java:112)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
[ 2022-08-24T01:09:49.926    10202:  3799: 26736 I/LSPosed-Bridge  ] scan result: content://media/external_primary/file/2262
[ 2022-08-24T01:09:49.977    10202:  3799: 26738 I/LSPosed-Bridge  ] scan result: content://media/external_primary/file/2263
[ 2022-08-24T01:09:50.014    10229: 27034: 27034 I/LSPosed-Bridge  ] Loading module lantian.nolitter from /data/app/~~xcEQwkxx6sbi4ourOADqjw==/lantian.nolitter-E0PEnGQaGzCbdLTRipPuUQ==/base.apk
[ 2022-08-24T01:09:50.023    10229: 27034: 27034 I/LSPosed-Bridge  ]   Loading class lantian.nolitter.XposedHook
[ 2022-08-24T01:09:50.078    10229: 27034: 27034 E/LSPosed-Bridge  ] java.lang.RuntimeException: Unable to fetch the content
	at lantian.nolitter.XposedHook.f(Unknown Source:33)
	at EM.beforeHookedMethod(SourceFile:5)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
	at android.app.ActivityThread.access$1500(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[ 2022-08-24T01:09:50.162    10202:  3799: 17818 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/autonavi/support/rtbus.cfg
[ 2022-08-24T01:09:50.184    10202:  3799: 17823 I/LSPosed-Bridge  ] scan for obsolete insert: /storage/emulated/0/autonavi/support/taxi.cfg
[ 2022-08-24T01:09:51.176    10202:  3799: 27113 I/LSPosed-Bridge  ] scan result: content://media/external_primary/file/2228
[ 2022-08-24T01:09:51.197    10202:  3799: 27114 I/LSPosed-Bridge  ] scan result: content://media/external_primary/file/2232`

**Comment by wenxuanjun** [comment]
`1.6.0 Alpha`的ContentProvider现有不少问题，请等待日后的修复
